# remap prefix to Control + a
unbind C-b
set -g prefix C-a

# C-a twice to send prefix to application
bind C-a send-prefix

# start window and pane count at 1
set -g base-index 1
set -g pane-base-index 1

# Bind pipe and dash to window splits
unbind %
bind | split-window -h
bind - split-window -v

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# resizing panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# look good
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# The amount of time tmux waits
# for a keystroke after pressing PREFIX
set -sg escape-time 1

set -g mouse on

set -g status-position top

#### COLOUR (solarized-ish, migrated from .tmuxcolors.conf)

# default statusbar colors
set -g status-style bg=colour235,fg=colour136 # base02 / yellow

# window title colors
setw -g window-status-style fg=colour244,bg=default
setw -g window-status-current-style fg=colour166,bg=default # orange

# pane border
set -g pane-border-style fg=colour235 # base02
set -g pane-active-border-style fg=colour240 # base01

# message text
set -g message-style bg=colour235,fg=colour166 # base02 / orange

# pane number display
set -g display-panes-active-colour colour33 # blue
set -g display-panes-colour colour166 # orange

# clock
setw -g clock-mode-colour colour64 # green
