# https://merikan.com/2019/05/how-to-sign-git-commits/
#
# If you get the following error
# ```
# gpg: signing failed: No pinentry
# gpg: [stdin]: clear-sign failed: No pinentry
# ```
# gpgconf --kill gpg-agent
# gpgconf --launch gpg-agent
# -----------------------------------------------------------------------------/
enable-ssh-support
pinentry-program /opt/homebrew/bin/pinentry-mac
