# You may need to manually set your language environment
export LANG=en_US.UTF-8

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Set LSCOLORS (FreeBSD / macOS).
#
#  * `ls` displays colors if the `-G` option is passed or if
#    the `CLICOLOR` environment variable is set.
#
#  * The actual colors are configured through the `LSCOLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set).
alias ls="ls --color=auto"

LSCOLORS=""

LSCOLORS+="cx" # Directory
LSCOLORS+="Bx" # Symbolic link
LSCOLORS+="hx" # Socket
LSCOLORS+="Dx" # Pipe
LSCOLORS+="fx" # Executable
LSCOLORS+="hx" # Block special
LSCOLORS+="hx" # Character special
LSCOLORS+="hx" # Executable with setuid bit set
LSCOLORS+="hx" # Executable with setgid bit set
LSCOLORS+="cx" # Directory writable to others, with sticky bit
LSCOLORS+="cx" # Directory writable to others, without sticky bit

export LSCOLORS
export CLICOLOR=1


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#  History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000000000
SAVEHIST=1000000000
# Treat the '!' character specially during expansion.
setopt BANG_HIST
# Write the history file in the ":start:elapsed;command" format.
setopt EXTENDED_HISTORY
# Write to the history file immediately, not when the shell exits.
setopt INC_APPEND_HISTORY
# Share history between all sessions.
setopt SHARE_HISTORY
# Expire duplicate entries first when trimming history.
setopt HIST_EXPIRE_DUPS_FIRST
# Don't record an entry that was just recorded again.
setopt HIST_IGNORE_DUPS
# Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_ALL_DUPS
# Do not display a line previously found.
setopt HIST_FIND_NO_DUPS
# Don't record an entry starting with a space.
setopt HIST_IGNORE_SPACE
# Don't write duplicate entries in the history file.
setopt HIST_SAVE_NO_DUPS
# Remove superfluous blanks before recording entry.
setopt HIST_REDUCE_BLANKS
# Don't execute immediately upon history expansion.
setopt HIST_VERIFY
# Beep when accessing nonexistent history.
setopt HIST_BEEP
# put a space at the front and you won't record history
setopt HIST_IGNORE_SPACE


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# https://stackoverflow.com/questions/23128353/zsh-shortcut-ctrl-a-not-working/43087047
bindkey -e

export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"

# Home bin folder for various
export PATH=$PATH:$HOME/bin

# GPG + Yubikey
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
gpg-connect-agent updatestartuptty /bye

# Go development
export GOPATH="${HOME}/.go"
export GOROOT="$(brew --prefix)/opt/go/libexec"
export GOCACHE=$GOPATH/cache

export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Misc aliases
alias vi="nvim"
alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias t="terraform"
alias tf="terraform"
alias docker="DOCKER_BUILDKIT=1 docker"
alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;say cache flushed'
alias m="molecule"
alias mo="molecule"
alias uuid="python -c 'import sys,uuid; sys.stdout.write(uuid.uuid4().hex)' | pbcopy && pbpaste && echo"
alias watch="watch "
alias zreload="exec /bin/zsh -l"
alias u="sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup \
            && npm install -g npm \
            && npm update -g"


# https://medium.com/@dannysmith/little-thing-2-speeding-up-zsh-f1860390f92
nvm() {
  echo "🚨 NVM not loaded! Loading now..."
  unset -f nvm
  export NVM_PREFIX=$(brew --prefix nvm)
  [ -s "$NVM_PREFIX/nvm.sh" ] && . "$NVM_PREFIX/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm "$@"
}

# For the `complete` command to be available in zsh
# https://github.com/eddiezane/lunchy/issues/57#issuecomment-121173592
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

source $HOME/.zsh/plugins/aws.plugin.zsh
source $HOME/.zsh/plugins/k8s.plugin.zsh
source $HOME/.zsh/plugins/tf.plugin.zsh
source $HOME/.zsh/plugins/spinnaker.plugin.zsh
source $HOME/.zsh/plugins/git.plugin.zsh
source $HOME/.fzf.zsh

export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --theme=gruvbox --color=always --style=header,grid --line-range :300 {}'"
export FZF_DEFAULT_COMMAND='fd -HI --type file'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export TERM=xterm-256color

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"

export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$HOME/bin"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"


# Created by `pipx` on 2021-08-17 23:03:20
export PATH="$PATH:/Users/mhume/.local/bin"
